/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,7],$V1=[1,10],$V2=[1,11],$V3=[1,12],$V4=[1,15],$V5=[5,7,10,23,24,25,27],$V6=[5,7,10,14,15,16,17,23,24,25,27],$V7=[5,7,10,14,15,23,24,25,27];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"topLevel":3,"regex":4,"tEND":5,"expr":6,"|":7,"literal":8,"subexpr":9,"tCHARLIT":10,"chunk":11,"repetition":12,"repetitionHead":13,"?":14,"+":15,"*":16,"{":17,"repetitionRepr":18,"}":19,",":20,"tNUM":21,"group":22,"tCHAR":23,"tBACKREF":24,"(":25,"groupGuts":26,")":27,"specialGroup":28,"subroutine":29,"noCapture":30,"atomic":31,"tNOCAPTURE":32,"tATOMIC":33,"R":34,"$accept":0,"$end":1},
terminals_: {2:"error",5:"tEND",7:"|",10:"tCHARLIT",14:"?",15:"+",16:"*",17:"{",19:"}",20:",",21:"tNUM",23:"tCHAR",24:"tBACKREF",25:"(",27:")",32:"tNOCAPTURE",33:"tATOMIC",34:"R"},
productions_: [0,[3,2],[3,1],[4,1],[4,2],[4,3],[6,1],[6,1],[8,1],[8,2],[9,1],[9,2],[12,1],[12,2],[12,2],[13,1],[13,1],[13,1],[13,3],[18,1],[18,2],[18,2],[18,3],[11,1],[11,1],[11,1],[22,3],[26,1],[26,1],[26,1],[28,1],[28,1],[30,2],[31,2],[29,2],[29,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return $$[$0-1]; 
break;
case 2:
 return [[]]; 
break;
case 3:
 this.$ = [[$$[$0]]]; 
break;
case 4:

      $$[$0-1][$$[$0-1].length-1].push($$[$0]);
      this.$ = $$[$0-1];
    
break;
case 5:
 this.$ = $$[$0-2].concat($$[$0]); 
break;
case 6:

      this.$ = {
        type: 'LITERAL',
        value: $$[$0]
      };
    
break;
case 9:
 this.$ = $$[$0-1] + $$[$0]; 
break;
case 10:

      $$[$0].repetition = {
        range: [1,1],
        type: 'greedy'
      };
      this.$ = $$[$0];
    
break;
case 11:

      $$[$0-1].repetition = $$[$0];
      this.$ = $$[$0-1];
    
break;
case 12:

      this.$ = {
        range: $$[$0],
        type: 'greedy'
      };
    
break;
case 13:

      this.$ = {
        range: $$[$0-1],
        type: 'lazy'
      };
    
break;
case 14:

      this.$ = {
        range: $$[$0-1],
        type: 'possessive'
      };
    
break;
case 15:
 this.$ = [0,1]; 
break;
case 16:
 this.$ = [1,9007199254740990]; 
break;
case 17: case 19:
 this.$ = [0,9007199254740990]; 
break;
case 18:
 this.$ = $$[$0-1]; 
break;
case 20:
 this.$ = [parseInt($$[$0-1]),9007199254740990]; 
break;
case 21:
 this.$ = [0,parseInt($$[$0])]; 
break;
case 22:
 this.$ = [parseInt($$[$0-2]),parseInt($$[$0])]; 
break;
case 24:

      this.$ = {
        type: 'SINGLECHAR',
        value: $$[$0]
      };
    
break;
case 25:

      this.$ = {
        type: 'BACKREF',
        value: parseInt($$[$0].slice(1))
      };
    
break;
case 26:
 this.$ = $$[$0-1] 
break;
case 27:

      this.$ = {
        type: 'GROUP',
        grouptype: 'CAPTURE',
        value: $$[$0]
      };
    
break;
case 32:

      this.$ = {
        type: 'GROUP',
        grouptype: 'NOCAPTURE',
        value: $$[$0]
      };
    
break;
case 33:

      this.$ = {
        type: 'GROUP',
        grouptype: 'ATOMIC',
        value: $$[$0]
      };
    
break;
case 34:

      this.$ = {
        type: 'SUBROUTINE',
        value: parseInt($$[$0])
      };
    
break;
case 35:

      this.$ = {
        type: 'SUBROUTINE',
        value: 0
      }
    
break;
}
},
table: [{3:1,4:2,5:[1,3],6:4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3},{1:[3]},{5:[1,13],6:14,7:$V4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3},{1:[2,2]},o($V5,[2,3]),o([5,7,23,24,25,27],[2,6],{10:[1,16]}),o($V5,[2,7]),o($V5,[2,8]),o($V5,[2,10],{12:17,13:18,14:[1,19],15:[1,20],16:[1,21],17:[1,22]}),o($V6,[2,23]),o($V6,[2,24]),o($V6,[2,25]),{4:24,6:4,8:5,9:6,10:$V0,11:8,14:[1,29],22:9,23:$V1,24:$V2,25:$V3,26:23,28:25,29:26,30:27,31:28,32:[1,30],33:[1,31]},{1:[2,1]},o($V5,[2,4]),{4:32,6:4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3},o($V5,[2,9]),o($V5,[2,11]),o($V5,[2,12],{14:[1,33],15:[1,34]}),o($V7,[2,15]),o($V7,[2,16]),o($V7,[2,17]),{18:35,20:[1,36],21:[1,37]},{27:[1,38]},{6:14,7:$V4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3,27:[2,27]},{27:[2,28]},{27:[2,29]},{27:[2,30]},{27:[2,31]},{21:[1,39],34:[1,40]},{4:41,6:4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3},{4:42,6:4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3},o([5,27],[2,5],{8:5,9:6,11:8,22:9,6:14,7:$V4,10:$V0,23:$V1,24:$V2,25:$V3}),o($V5,[2,13]),o($V5,[2,14]),{19:[1,43]},{19:[2,19],21:[1,44]},{20:[1,45]},o($V6,[2,26]),{27:[2,34]},{27:[2,35]},{6:14,7:$V4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3,27:[2,32]},{6:14,7:$V4,8:5,9:6,10:$V0,11:8,22:9,23:$V1,24:$V2,25:$V3,27:[2,33]},o($V7,[2,18]),{19:[2,21]},{19:[2,20],21:[1,46]},{19:[2,22]}],
defaultActions: {3:[2,2],13:[2,1],25:[2,28],26:[2,29],27:[2,30],28:[2,31],39:[2,34],40:[2,35],44:[2,21],46:[2,22]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}